name: baseball_player_journey
packages:
  - "packages/**"
repository: "https://github.com/salan70/baseball_player_journey"
sdkPath: .fvm/flutter_sdk

command:
  clean:
    hooks:
      post: |
        melos exec --flutter -- "fvm flutter clean"
        melos exec --flutter --file-exists="ios/Podfile.lock" -- "cd ios && rm Podfile.lock"
  bootstrap:
    environment:
      sdk: '>=3.2.3 <4.0.0'
    dependencies:
      # Code generation.
      riverpod_annotation: ^2.2.0

      # State management.
      flutter_riverpod: ^2.4.3

      # Static analysis.
      pedantic_mono: ^1.27.0
    
    dev_dependencies:
      # Static analysis.
      flutter_lints: ^3.0.0

      # Code generation.
      build_runner: ^2.4.7
      freezed: ^2.4.5
      json_serializable: ^6.7.1
      riverpod_generator: ^2.3.9


scripts:
  clean:
    run: flutter clean
    exec:
      concurrency: 1
    packageFilters:
      dirExists: lib

  test:
    run: flutter test
    exec:
      concurrency: 1
    packageFilters:
      dirExists: test

  analyze:
    run: flutter analyze .
    exec:
      concurrency: 1
    packageFilters:
      dirExists: lib

  format:
    run: dart format .
    exec:
      concurrency: 1
    packageFilters:
      dirExists: lib

  gen:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: "build_runner"
