name: model
description: "A new Flutter package project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Code generation.
  riverpod_annotation: ^2.2.0

  # State management.
  flutter_riverpod: ^2.4.3

  # Static analysis.
  pedantic_mono: ^1.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis.
  flutter_lints: ^3.0.0

flutter:
