name: common
description: "A new Flutter package project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Code generation.
  riverpod_annotation: ^2.2.0

  # Debugging.
  roggle: ^0.3.0

  # Environment variables.
  flutter_dotenv: ^5.0.2

  # Firebase.
  cloud_firestore: ^4.4.5  
  firebase_crashlytics: ^3.0.17
  firebase_auth: ^4.3.0

  # State management.
  flutter_riverpod: ^2.4.3

  # Static analysis.
  pedantic_mono: ^1.20.1
  riverpod_lint: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation.
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

  # Static analysis.
  flutter_lints: ^2.0.0