name: baseball_player_journey
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Other packages in the project.
  model:
    path: ../model
  common:
    path: ../common

  # Navigation.
  auto_route: ^8.2.0

  # Code generation.
  auto_route_generator: ^8.0.0
  riverpod_annotation: ^2.2.0

  # State management.
  flutter_riverpod: ^2.4.3

  # Static analysis.
  pedantic_mono: ^1.27.0
  riverpod_lint: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Static analysis.
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0

  # Code generation.
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  fonts:
   - family: MochiyPopOne
     fonts:
       - asset: assets/fonts/Mochiy Pop One/MochiyPopOne-Regular.ttf
         weight: 400
